/**
 * Company contract: which company properties are copied and how
 * company records are chosen, keyed, remapped and linked.
 * The record shape lives in `types/company.types.ts`.
 */
import type { Company } from "../types/company.types.ts";
import type { ObjectContract } from "../types/objectContract.types.ts";

/** Every property in `Company`, in the same order, for API calls. */
export const COMPANY_PROPERTIES: (keyof Company)[] = [
  "about_us",
  "address",
  "address2",
  "annualrevenue",
  "city",
  "closedate",
  "country",
  "description",
  "domain",
  "facebook_company_page",
  "facebookfans",
  "founded_year",
  "googleplus_page",
  "hs_additional_domains",
  "hs_all_assigned_business_unit_ids",
  "hs_analytics_source",
  "hs_country_code",
  "hs_csm_sentiment",
  "hs_current_customer",
  "hs_domain_status",
  "hs_employee_range",
  "hs_excluded_from_cross_account_data_mirroring",
  "hs_gps_latitude",
  "hs_gps_longitude",
  "hs_ideal_customer_profile",
  "hs_industry_group",
  "hs_is_target_account",
  "hs_keywords",
  "hs_last_metered_enrichment_timestamp",
  "hs_lead_status",
  "hs_linkedin_handle",
  "hs_live_enrichment_deadline",
  "hs_logo_url",
  "hs_owning_teams",
  "hs_pinned_engagement_id",
  "hs_pipeline",
  "hs_quick_context",
  "hs_recent_news",
  "hs_redirect_domain",
  "hs_redirect_url",
  "hs_revenue_range",
  "hs_shared_team_ids",
  "hs_shared_user_ids",
  "hs_state_code",
  "hs_target_account",
  "hs_target_account_recommendation_snooze_time",
  "hs_target_account_recommendation_state",
  "hs_tax_id",
  "hubspot_owner_id",
  "industry",
  "is_public",
  "lifecyclestage",
  "linkedin_company_page",
  "linkedinbio",
  "name",
  "numberofemployees",
  "owneremail",
  "ownername",
  "phone",
  "state",
  "timezone",
  "total_money_raised",
  "twitterbio",
  "twitterfollowers",
  "twitterhandle",
  "type",
  "web_technologies",
  "website",
  "zip",
  "assigned_sales_rep",
  "county",
  "excede_customer_allow_finance_chg",
  "excede_customer_allow_special_pri",
  "excede_customer_amt_aged0",
  "excede_customer_amt_aged1to30",
  "excede_customer_amt_aged31to60",
  "excede_customer_amt_aged61to90",
  "excede_customer_amt_aged_over90",
  "excede_customer_amt_bal_account",
  "excede_customer_amt_bal_open",
  "excede_customer_amt_cr_limit",
  "excede_customer_amt_cr_limit_invoice",
  "excede_customer_amt_invoice",
  "excede_customer_amt_payment",
  "excede_customer_bill_addr1",
  "excede_customer_bill_addr2",
  "excede_customer_bill_city",
  "excede_customer_bill_country",
  "excede_customer_bill_county",
  "excede_customer_bill_cus_id",
  "excede_customer_bill_post",
  "excede_customer_bill_state",
  "excede_customer_company_flag",
  "excede_customer_contact",
  "excede_customer_core_invoice_reqd",
  "excede_customer_cus_misc1",
  "excede_customer_cus_misc2",
  "excede_customer_cus_misc3",
  "excede_customer_cus_misc4",
  "excede_customer_cus_misc5",
  "excede_customer_cutoff_aged_period",
  "excede_customer_cutoff_by_aged",
  "excede_customer_cutoff_by_cr_limit",
  "excede_customer_date_birth",
  "excede_customer_date_birth_spouse",
  "excede_customer_date_create",
  "excede_customer_date_do_not_call",
  "excede_customer_date_invoice",
  "excede_customer_date_payment",
  "excede_customer_date_statement",
  "excede_customer_date_update",
  "excede_customer_days_payment_avg",
  "excede_customer_do_not_call_phone_home",
  "excede_customer_do_not_call_phone_other",
  "excede_customer_do_not_call_phone_work",
  "excede_customer_dsb_typ_id",
  "excede_customer_email_home",
  "excede_customer_email_other",
  "excede_customer_email_work",
  "excede_customer_emp_id",
  "excede_customer_emp_id_spn",
  "excede_customer_fl_sls_typ_id",
  "excede_customer_id",
  "excede_customer_inactive",
  "excede_customer_mem_typ_id",
  "excede_customer_name_first",
  "excede_customer_name_last",
  "excede_customer_name_middle",
  "excede_customer_name_nick",
  "excede_customer_name_spouse",
  "excede_customer_not_id",
  "excede_customer_phone_fax",
  "excede_customer_phone_other",
  "excede_customer_pri_id_base",
  "excede_customer_pri_id_oride",
  "excede_customer_pt_sls_typ_id",
  "excede_customer_pt_tax_id",
  "excede_customer_pur_nbr",
  "excede_customer_pur_reqd",
  "excede_customer_rec_typ_id",
  "excede_customer_shp_id",
  "excede_customer_statement_reqd",
  "excede_customer_sv_sls_typ_id",
  "excede_customer_sv_tax_id",
  "excede_customer_trm_id",
  "excede_customer_ts",
  "excede_customer_type",
  "excede_customer_vh_sls_typ_id",
  "excede_customer_vh_tax_id",
  "mobilephone",
];

export const COMPANY_CONTRACT: ObjectContract = {
  kind: "companies",
  stage: 3,
  selection: "linked",
  linkedFrom: ["deals", "contacts"],
  keyPriority: [
    "excede_customer_id",
  ],
  properties: COMPANY_PROPERTIES,
  remaps: ["owners"],
  links: [
    { to: "deals" },
    { to: "contacts" },
  ],
};
