/**
 * Contact contract: which contact properties are copied and how
 * contact records are chosen, keyed, remapped and linked.
 * The record shape lives in `types/contact.types.ts`.
 */
import type { Contact } from "../types/contact.types.ts";
import type { ObjectContract } from "../types/objectContract.types.ts";

/** Every property in `Contact`, in the same order, for API calls. */
export const CONTACT_PROPERTIES: (keyof Contact)[] = [
  "address",
  "annualrevenue",
  "associatedcompanyid",
  "city",
  "closedate",
  "company",
  "company_size",
  "country",
  "date_of_birth",
  "degree",
  "email",
  "fax",
  "field_of_study",
  "firstname",
  "followercount",
  "gender",
  "graduation_date",
  "hs_additional_emails",
  "hs_all_assigned_business_unit_ids",
  "hs_analytics_source",
  "hs_bing_ad_clicked",
  "hs_bing_click_id",
  "hs_buying_role",
  "hs_chat_assistant_iql_date",
  "hs_chat_assistant_source",
  "hs_chat_assistant_summary",
  "hs_chatgpt_ad_clicked",
  "hs_chatgpt_click_id",
  "hs_clicked_linkedin_ad",
  "hs_content_membership_email",
  "hs_content_membership_notes",
  "hs_content_membership_status",
  "hs_country_region_code",
  "hs_cross_account_note",
  "hs_cross_sell_opportunity",
  "hs_current_customer",
  "hs_email_customer_quarantined_reason",
  "hs_email_type",
  "hs_employment_change_detected_date",
  "hs_enforce_double_opt_in",
  "hs_enriched_email_bounce_detected",
  "hs_excluded_from_cross_account_data_mirroring",
  "hs_facebook_ad_clicked",
  "hs_facebook_click_id",
  "hs_facebookid",
  "hs_feedback_show_nps_web_survey",
  "hs_google_click_id",
  "hs_googleplusid",
  "hs_gps_latitude",
  "hs_gps_longitude",
  "hs_inferred_language_codes",
  "hs_job_change_detected_date",
  "hs_journey_stage",
  "hs_language",
  "hs_last_metered_enrichment_timestamp",
  "hs_latest_source",
  "hs_latest_source_timestamp",
  "hs_lead_status",
  "hs_legal_basis",
  "hs_linkedin_ad_clicked",
  "hs_linkedin_click_id",
  "hs_linkedin_url",
  "hs_linkedinid",
  "hs_live_enrichment_deadline",
  "hs_owning_teams",
  "hs_persona",
  "hs_pinned_engagement_id",
  "hs_pipeline",
  "hs_prospecting_agent_activation_email_id",
  "hs_prospecting_agent_activation_status",
  "hs_prospecting_agent_last_enrolled",
  "hs_prospecting_agent_total_enrolled_count",
  "hs_recent_news",
  "hs_reddit_ad_clicked",
  "hs_reddit_click_id",
  "hs_returning_to_office_detected_date",
  "hs_role",
  "hs_seniority",
  "hs_shared_team_ids",
  "hs_shared_user_ids",
  "hs_state_code",
  "hs_sub_role",
  "hs_tiktok_ad_clicked",
  "hs_tiktok_click_id",
  "hs_time_between_contact_creation_and_deal_close",
  "hs_time_between_contact_creation_and_deal_creation",
  "hs_time_to_move_from_lead_to_customer",
  "hs_time_to_move_from_marketingqualifiedlead_to_customer",
  "hs_time_to_move_from_opportunity_to_customer",
  "hs_time_to_move_from_salesqualifiedlead_to_customer",
  "hs_time_to_move_from_subscriber_to_customer",
  "hs_timezone",
  "hs_twitterid",
  "hs_whatsapp_bsuids",
  "hs_whatsapp_phone_number",
  "hubspot_owner_id",
  "industry",
  "job_function",
  "jobtitle",
  "kloutscoregeneral",
  "lastname",
  "lifecyclestage",
  "linkedinbio",
  "linkedinconnections",
  "marital_status",
  "message",
  "military_status",
  "mobilephone",
  "numemployees",
  "ownername",
  "phone",
  "photo",
  "relationship_status",
  "salutation",
  "school",
  "seniority",
  "start_date",
  "state",
  "twitterbio",
  "twitterhandle",
  "twitterprofilephoto",
  "website",
  "work_email",
  "zip",
  "address2",
  "county",
  "excede_customer_contact_cus_id",
  "excede_customer_contact_date_create",
  "excede_customer_contact_date_update",
  "excede_customer_contact_department",
  "excede_customer_contact_email_other",
  "excede_customer_contact_emp_id",
  "excede_customer_contact_id",
  "excede_customer_contact_name",
  "excede_customer_contact_phone_fax",
  "excede_customer_contact_phone_home_ext",
  "excede_customer_contact_phone_other",
  "excede_customer_contact_phone_other_ext",
  "excede_customer_contact_phone_work_ext",
  "excede_customer_contact_ts",
  "excede_customer_contact_typ",
];

export const CONTACT_CONTRACT: ObjectContract = {
  kind: "contacts",
  stage: 2,
  selection: "linked",
  linkedFrom: ["deals"],
  keyPriority: [
    "excede_customer_contact_id",
    "email",
  ],
  properties: CONTACT_PROPERTIES,
  remaps: ["owners"],
  links: [
    { to: "deals" },
  ],
};
