/**
 * Product contract: which product properties are copied and how
 * product records are chosen, keyed, remapped and linked.
 * The record shape lives in `types/product.types.ts`.
 */
import type { Product } from "../types/product.types.ts";
import type { ObjectContract } from "../types/objectContract.types.ts";

/** Every property in `Product`, in the same order, for API calls. */
export const PRODUCT_PROPERTIES: (keyof Product)[] = [
  "createdate",
  "description",
  "discount",
  "hs_all_assigned_business_unit_ids",
  "hs_bundle_pricing_type",
  "hs_cost_of_goods_sold",
  "hs_discount_percentage",
  "hs_folder",
  "hs_folder_id",
  "hs_images",
  "hs_owning_teams",
  "hs_pinned_engagement_id",
  "hs_pricing_model",
  "hs_product_type",
  "hs_recurring_billing_period",
  "hs_recurring_billing_start_date",
  "hs_rich_text_description",
  "hs_sku",
  "hs_status",
  "hs_tax_category",
  "hs_tier_prices",
  "hs_tier_ranges",
  "hs_url",
  "hubspot_owner_id",
  "name",
  "price",
  "recurringbillingfrequency",
  "tax",
  "excede_part_amt_cost_avg",
  "excede_part_amt_cost_src",
  "excede_part_amt_cost_src2",
  "excede_part_amt_price2",
  "excede_part_amt_price3",
  "excede_part_amt_price4",
  "excede_part_amt_price5",
  "excede_part_auto_min_max",
  "excede_part_avg_sales_day",
  "excede_part_bin_id1",
  "excede_part_bin_id2",
  "excede_part_brn_id",
  "excede_part_cla_id",
  "excede_part_count_freq_days",
  "excede_part_date_count",
  "excede_part_date_create",
  "excede_part_date_level",
  "excede_part_date_order",
  "excede_part_date_sale",
  "excede_part_date_tape",
  "excede_part_date_update",
  "excede_part_id",
  "excede_part_not_id",
  "excede_part_order_pkg_min",
  "excede_part_order_pkg_mul",
  "excede_part_prt_misc1",
  "excede_part_prt_misc2",
  "excede_part_prt_misc3",
  "excede_part_prt_misc4",
  "excede_part_prt_misc5",
  "excede_part_qty_max",
  "excede_part_qty_min",
  "excede_part_qty_oh",
  "excede_part_qty_oo",
  "excede_part_qty_ot",
  "excede_part_qty_reserve",
  "excede_part_qty_supply",
  "excede_part_sale_pkg_mul",
  "excede_part_src_id",
  "excede_part_stock_ctl",
  "excede_part_stock_order_ratio",
  "excede_part_ts",
  "excede_part_typ",
  "excede_part_ven_id",
  "excede_part_ven_prt_id",
];

export const PRODUCT_CONTRACT: ObjectContract = {
  kind: "products",
  stage: 6,
  selection: "independent",
  linkedFrom: [],
  keyPriority: [
    "excede_part_id",
  ],
  properties: PRODUCT_PROPERTIES,
  remaps: ["owners"],
  links: [],
};
