/**
 * Vehicle contract: which vehicle (custom object) properties are copied and how
 * vehicle (custom object) records are chosen, keyed, remapped and linked.
 * The record shape lives in `types/vehicle.types.ts`.
 */
import type { Vehicle } from "../types/vehicle.types.ts";
import type { ObjectContract } from "../types/objectContract.types.ts";

/** Every property in `Vehicle`, in the same order, for API calls. */
export const VEHICLE_PROPERTIES: (keyof Vehicle)[] = [
  "hs_all_assigned_business_unit_ids",
  "hs_owning_teams",
  "hs_pinned_engagement_id",
  "hs_shared_team_ids",
  "hs_shared_user_ids",
  "hubspot_owner_id",
  "excede_vehicle_accomp_serial_nbr",
  "excede_vehicle_amt_adj_cost",
  "excede_vehicle_amt_adj_price",
  "excede_vehicle_amt_dmvfees",
  "excede_vehicle_amt_dmvfees_next",
  "excede_vehicle_amt_fuel_tax_rep",
  "excede_vehicle_amt_hold_back",
  "excede_vehicle_amt_mfr_cost",
  "excede_vehicle_amt_mfr_price",
  "excede_vehicle_amt_our_cost",
  "excede_vehicle_amt_our_price",
  "excede_vehicle_amt_prop_tax_fee",
  "excede_vehicle_amt_rebate",
  "excede_vehicle_amt_salvage",
  "excede_vehicle_apu",
  "excede_vehicle_body_style",
  "excede_vehicle_branch_id",
  "excede_vehicle_cab_config",
  "excede_vehicle_condition",
  "excede_vehicle_count_emp_id",
  "excede_vehicle_cus_id",
  "excede_vehicle_cus_name",
  "excede_vehicle_cylinders",
  "excede_vehicle_date_count",
  "excede_vehicle_date_create",
  "excede_vehicle_date_dep_end",
  "excede_vehicle_date_dep_start",
  "excede_vehicle_date_dmvfees_expire",
  "excede_vehicle_date_dmvlicense_expire",
  "excede_vehicle_date_in_service",
  "excede_vehicle_date_note_end",
  "excede_vehicle_date_note_start",
  "excede_vehicle_date_receive",
  "excede_vehicle_date_update",
  "excede_vehicle_dmvlicense",
  "excede_vehicle_dmvnotes",
  "excede_vehicle_dmvstate",
  "excede_vehicle_emp_id",
  "excede_vehicle_engine_brake",
  "excede_vehicle_engine_mfr",
  "excede_vehicle_engine_model",
  "excede_vehicle_engine_serial_nbr",
  "excede_vehicle_ext_color",
  "excede_vehicle_ext_color_code",
  "excede_vehicle_fifth_wheel",
  "excede_vehicle_fleet_unt_id",
  "excede_vehicle_front_axle_mfr",
  "excede_vehicle_front_axle_model",
  "excede_vehicle_front_axle_serial_nbr",
  "excede_vehicle_fuel_tank",
  "excede_vehicle_gvwr",
  "excede_vehicle_horsepower",
  "excede_vehicle_hrs_apu",
  "excede_vehicle_hrs_engine",
  "excede_vehicle_hrs_other",
  "excede_vehicle_hrs_pto",
  "excede_vehicle_hrs_reefer",
  "excede_vehicle_hrs_standby",
  "excede_vehicle_id",
  "excede_vehicle_int_color",
  "excede_vehicle_int_color_code",
  "excede_vehicle_key_code1",
  "excede_vehicle_key_code2",
  "excede_vehicle_location_id",
  "excede_vehicle_make",
  "excede_vehicle_marketability",
  "excede_vehicle_model",
  "excede_vehicle_model_nbr",
  "excede_vehicle_model_year",
  "excede_vehicle_not_id",
  "excede_vehicle_odom",
  "excede_vehicle_odom_typ",
  "excede_vehicle_other",
  "excede_vehicle_other_des",
  "excede_vehicle_pct_ins_markup",
  "excede_vehicle_pct_note",
  "excede_vehicle_preferred_contact_id",
  "excede_vehicle_pto",
  "excede_vehicle_pur_emp_id",
  "excede_vehicle_pur_ven_id",
  "excede_vehicle_rear_axle_mfr",
  "excede_vehicle_rear_axle_model",
  "excede_vehicle_rear_axle_ratio",
  "excede_vehicle_rear_axle_serial_nbr",
  "excede_vehicle_rear_front_axle_mfr",
  "excede_vehicle_rear_front_axle_model",
  "excede_vehicle_rear_front_axle_serial_nbr",
  "excede_vehicle_reefer",
  "excede_vehicle_series",
  "excede_vehicle_sleeper",
  "excede_vehicle_status",
  "excede_vehicle_status_notes",
  "excede_vehicle_suspension_typ",
  "excede_vehicle_trans_mfr",
  "excede_vehicle_trans_model",
  "excede_vehicle_trans_serial_nbr",
  "excede_vehicle_transmission",
  "excede_vehicle_ts",
  "excede_vehicle_typ_id",
  "excede_vehicle_unt_misc1",
  "excede_vehicle_unt_misc10",
  "excede_vehicle_unt_misc11",
  "excede_vehicle_unt_misc12",
  "excede_vehicle_unt_misc13",
  "excede_vehicle_unt_misc14",
  "excede_vehicle_unt_misc15",
  "excede_vehicle_unt_misc16",
  "excede_vehicle_unt_misc17",
  "excede_vehicle_unt_misc18",
  "excede_vehicle_unt_misc19",
  "excede_vehicle_unt_misc2",
  "excede_vehicle_unt_misc20",
  "excede_vehicle_unt_misc21",
  "excede_vehicle_unt_misc22",
  "excede_vehicle_unt_misc23",
  "excede_vehicle_unt_misc24",
  "excede_vehicle_unt_misc25",
  "excede_vehicle_unt_misc26",
  "excede_vehicle_unt_misc27",
  "excede_vehicle_unt_misc28",
  "excede_vehicle_unt_misc29",
  "excede_vehicle_unt_misc3",
  "excede_vehicle_unt_misc30",
  "excede_vehicle_unt_misc31",
  "excede_vehicle_unt_misc32",
  "excede_vehicle_unt_misc33",
  "excede_vehicle_unt_misc34",
  "excede_vehicle_unt_misc35",
  "excede_vehicle_unt_misc36",
  "excede_vehicle_unt_misc37",
  "excede_vehicle_unt_misc38",
  "excede_vehicle_unt_misc39",
  "excede_vehicle_unt_misc4",
  "excede_vehicle_unt_misc40",
  "excede_vehicle_unt_misc5",
  "excede_vehicle_unt_misc6",
  "excede_vehicle_unt_misc7",
  "excede_vehicle_unt_misc8",
  "excede_vehicle_unt_misc9",
  "excede_vehicle_vin",
  "excede_vehicle_wheelbase",
];

export const VEHICLE_CONTRACT: ObjectContract = {
  kind: "vehicles",
  stage: 4,
  selection: "linked",
  linkedFrom: ["deals"],
  keyPriority: [
    "excede_vehicle_id",
  ],
  properties: VEHICLE_PROPERTIES,
  remaps: ["owners"],
  links: [
    { to: "deals" },
    { to: "companies" },
    { to: "contacts" },
  ],
};
